<?php

use Drupal\Core\Routing\RouteMatchInterface;

function notices_help($route_name, RouteMatchInterface $route_match){
    switch ($route_name) {
        case 'help.page.notices';
            return t('Esta es la información de ayuda de noticias');
        case 'notices.description';
            return t('Esta es la información del apartado de noticias');
    }
}

function notices_permission(){
      return array(
      'acceder content' => array(
          'title' => t('Acceso a las noticias'),
          'description' => t('Permite a acceder a la vista de detalles y las noticias'),
      ), 
          'access config' => array(
          'title' => t('Acceso a configuración del modulo'),
          'description' => t('Permite acceder a la configuración del modulo notices'),
      ), 
    );
}
/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

