## YAML Template.
block.settings.noticias_simple:
  type: block_settings
  label: 'Configuración del bloque noticias'
  mapping:
    noticias_block_string:
      type: text
      label: 'Texto de la parte superior del bloque'
